{"name": "用户输入运算数据a、b, 程序输出正确的结果", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './data/add_data.yaml'", "trace": "request = <SubRequest 'cmd_option' for <Function test_div[10-5-2]>>\n\n    @pytest.fixture(scope=\"session\")\n    def cmd_option(request):\n        \"\"\"\n        查看指定测试用例的测试数据\n        :param request:  参数化\n        :return:\n        \"\"\"\n        global data_path\n        my_file_path = request.config.getoption(\"--show\", default=\"add_data\")\n        if my_file_path == \"add_data\":\n            data_path = \"./data/add_data.yaml\"\n        elif my_file_path == \"range_in_add_data\":\n            data_path = \"./data/add_data_range_in.yaml\"\n        elif my_file_path == \"range_out_data\":\n            data_path = \"./data/data_range_out.yaml\"\n        elif my_file_path == \"type_error_data\":\n            data_path = \"./data/data_type_error.yaml\"\n        elif my_file_path == \"div_data\":\n            data_path = \"./data/div_data.yaml\"\n        elif my_file_path == \"rang_in_div_data\":\n            data_path = \"./data/div_data_rang_in.yaml\"\n        elif my_file_path == \"zero_division_error\":\n            data_path = \"./data/zero_division_error.yaml\"\n    \n>       with open(data_path, \"r\", encoding=\"utf-8\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: './data/add_data.yaml'\n\n..\\conftest.py:83: FileNotFoundError"}, "parameters": [{"name": "a", "value": "-98.9"}, {"name": "b", "value": "-98.9"}, {"name": "expected", "value": "1"}], "start": 1715221681840, "stop": 1715221681840, "uuid": "93887e76-93aa-40f8-b69b-5a18d0530d4b", "historyId": "8d1fd52400df05e5ef0b8f400e13e7cb", "testCaseId": "7291d55f31158b2c09ba1cb8544f4e8f", "fullName": "test_case.test_case_01.TestCase#test_div", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "test_normal"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_case_01"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "wangmin"}, {"name": "thread", "value": "3468-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_case_01"}], "links": [{"type": "tms", "url": "http://192.168.40.134:8080/projects/CACULATOR/issues/CACULATOR-4?filter=allissues", "name": "用例管理系统"}]}