DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:90 Selenium Manager binary found at: D:\python3\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:103 Executing process: D:\python3\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --debug --language-binding python --output json
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Found chromedriver 129.0.6668.58 in PATH: C:\Program Files\Google\Chrome\Application\chromedriver.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 chrome detected at C:\Program Files\Google\Chrome\Application\chrome.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Running command: wmic datafile where name='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' get Version /value
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Output: "\r\r\n\r\r\nVersion=130.0.6723.58\r\r\n\r\r\n\r\r\n\r"
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Detected browser: chrome 130.0.6723.58
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Required driver: chromedriver 130.0.6723.58
WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:127 The chromedriver version (129.0.6668.58) detected in PATH at C:\Program Files\Google\Chrome\Application\chromedriver.exe might not be compatible with the detected chrome version (130.0.6723.58); currently, chromedriver 130.0.6723.58 is recommended for chrome 130.*, so it is advised to delete the driver in PATH and retry
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Driver path: C:\Program Files\Google\Chrome\Application\chromedriver.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Browser path: C:\Program Files\Google\Chrome\Application\chrome.exe
DEBUG    selenium.webdriver.common.service:service.py:219 Started executable: `C:\Program Files\Google\Chrome\Application\chromedriver.exe` in a child process with pid: 14472 using 0 to output -3
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:301 POST http://localhost:54553/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'chrome', 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'browserVersion': None, 'goog:chromeOptions': {'extensions': [], 'binary': 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', 'args': []}}}}
DEBUG    urllib3.connectionpool:connectionpool.py:244 Starting new HTTP connection (1): localhost:54553
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:54553 "POST /session HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:330 Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"130.0.6723.58","chrome":{"chromedriverVersion":"129.0.6668.58 (81a06fb873a9b386848719cf9f93e59579fb5d4b-refs/branch-heads/6668@{#1318})","userDataDir":"C:\\Users\\wangm\\AppData\\Local\\Temp\\scoped_dir14472_485246299"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:54556"},"networkConnectionEnabled":false,"pageLoadStrategy":"normal","platformName":"windows","proxy":{},"setWindowRect":true,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"9a74e0f8aaa461e6c6bc64ceb6761fef"}} | headers=HTTPHeaderDict({'Content-Length': '881', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:357 Finished Request
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:90 Selenium Manager binary found at: D:\python3\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:103 Executing process: D:\python3\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --debug --language-binding python --output json
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Found chromedriver 129.0.6668.58 in PATH: C:\Program Files\Google\Chrome\Application\chromedriver.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 chrome detected at C:\Program Files\Google\Chrome\Application\chrome.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Running command: wmic datafile where name='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe' get Version /value
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Output: "\r\r\n\r\r\nVersion=130.0.6723.58\r\r\n\r\r\n\r\r\n\r"
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Detected browser: chrome 130.0.6723.58
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Required driver: chromedriver 130.0.6723.58
WARNING  selenium.webdriver.common.selenium_manager:selenium_manager.py:127 The chromedriver version (129.0.6668.58) detected in PATH at C:\Program Files\Google\Chrome\Application\chromedriver.exe might not be compatible with the detected chrome version (130.0.6723.58); currently, chromedriver 130.0.6723.58 is recommended for chrome 130.*, so it is advised to delete the driver in PATH and retry
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Driver path: C:\Program Files\Google\Chrome\Application\chromedriver.exe
DEBUG    selenium.webdriver.common.selenium_manager:selenium_manager.py:129 Browser path: C:\Program Files\Google\Chrome\Application\chrome.exe
DEBUG    selenium.webdriver.common.service:service.py:219 Started executable: `C:\Program Files\Google\Chrome\Application\chromedriver.exe` in a child process with pid: 20956 using 0 to output -3
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:301 POST http://localhost:54563/session {'capabilities': {'firstMatch': [{}], 'alwaysMatch': {'browserName': 'chrome', 'pageLoadStrategy': <PageLoadStrategy.normal: 'normal'>, 'browserVersion': None, 'goog:chromeOptions': {'extensions': [], 'binary': 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', 'args': [], 'debuggerAddress': 'localhost:9222'}}}}
DEBUG    urllib3.connectionpool:connectionpool.py:244 Starting new HTTP connection (1): localhost:54563
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:54563 "POST /session HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:330 Remote response: status=200 | data={"value":{"capabilities":{"acceptInsecureCerts":false,"browserName":"chrome","browserVersion":"130.0.6723.58","chrome":{"chromedriverVersion":"129.0.6668.58 (81a06fb873a9b386848719cf9f93e59579fb5d4b-refs/branch-heads/6668@{#1318})"},"fedcm:accounts":true,"goog:chromeOptions":{"debuggerAddress":"localhost:9222"},"pageLoadStrategy":"normal","platformName":"","proxy":{},"setWindowRect":false,"strictFileInteractability":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"unhandledPromptBehavior":"dismiss and notify","webauthn:extension:credBlob":true,"webauthn:extension:largeBlob":true,"webauthn:extension:minPinLength":true,"webauthn:extension:prf":true,"webauthn:virtualAuthenticators":true},"sessionId":"bb54243ed0ee9642270b0c9f5f0e258e"}} | headers=HTTPHeaderDict({'Content-Length': '759', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:357 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:301 POST http://localhost:54563/session/bb54243ed0ee9642270b0c9f5f0e258e/timeouts {'implicit': 5000}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:54563 "POST /session/bb54243ed0ee9642270b0c9f5f0e258e/timeouts HTTP/1.1" 200 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:330 Remote response: status=200 | data={"value":null} | headers=HTTPHeaderDict({'Content-Length': '14', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:357 Finished Request
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:301 POST http://localhost:54563/session/bb54243ed0ee9642270b0c9f5f0e258e/window/maximize {}
DEBUG    urllib3.connectionpool:connectionpool.py:546 http://localhost:54563 "POST /session/bb54243ed0ee9642270b0c9f5f0e258e/window/maximize HTTP/1.1" 500 0
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:330 Remote response: status=500 | data={"value":{"error":"unknown error","message":"unknown error: failed to change window state to 'normal', current state is 'maximized'\n  (Session info: chrome=130.0.6723.58)","stacktrace":"\tGetHandleVerifier [0x00007FF7436AFDA5+29557]\n\t(No symbol) [0x00007FF743622240]\n\t(No symbol) [0x00007FF7434DB6EA]\n\t(No symbol) [0x00007FF7434B3FBE]\n\t(No symbol) [0x00007FF7434B1283]\n\t(No symbol) [0x00007FF7434B08E9]\n\t(No symbol) [0x00007FF743590A61]\n\t(No symbol) [0x00007FF7435574FA]\n\t(No symbol) [0x00007FF7435788A3]\n\t(No symbol) [0x00007FF7435572A3]\n\t(No symbol) [0x00007FF7435212DF]\n\t(No symbol) [0x00007FF743522451]\n\tGetHandleVerifier [0x00007FF7439DDCBD+3363469]\n\tGetHandleVerifier [0x00007FF743A29B47+3674391]\n\tGetHandleVerifier [0x00007FF743A1EAEB+3629243]\n\tGetHandleVerifier [0x00007FF74376FC66+815670]\n\t(No symbol) [0x00007FF74362D6EF]\n\t(No symbol) [0x00007FF7436292B4]\n\t(No symbol) [0x00007FF743629450]\n\t(No symbol) [0x00007FF7436181FF]\n\tBaseThreadInitThunk [0x00007FFD36C4257D+29]\n\tRtlUserThreadStart [0x00007FFD3884AF08+40]\n"}} | headers=HTTPHeaderDict({'Content-Length': '1070', 'Content-Type': 'application/json; charset=utf-8', 'cache-control': 'no-cache'})
DEBUG    selenium.webdriver.remote.remote_connection:remote_connection.py:357 Finished Request